export const locations = [
  'Patna Junction',
  'Patna Airport',
  'Boring Road, Patna',
  'Gandhi Maidan, Patna',
  'Rajendra Nagar, Patna',
  'Kankarbagh, Patna',
  'Danapur, Patna',
  'Hajipur',
  'Gaya Junction',
  'Bodh Gaya',
  'Rajgir',
  'Nalanda',
  'Bihar Sharif',
  'Jehanabad',
  'Aurangabad',
  'Dehri',
  'Sasaram',
  'Buxar',
  'Ara',
  'Chapra',
  'Siwan',
  'Muzaffarpur Junction',
  'Hajipur Junction',
  'Samastipur',
  'Begusarai',
  'Khagaria',
  'Darbhanga Airport',
  'Darbhanga Tower',
  'Madhubani',
  'Sitamarhi',
  'Motihari',
  'Bettiah',
  'Raxaul Border',
  'Bhagalpur Station',
  'Munger',
  'Jamui',
  'Lakhisarai',
  'Saharsa Junction',
  'Madhepura',
  'Supaul',
  'Purnea Junction',
  'Katihar',
  'Araria',
  'Forbesganj',
  'Kishanganj',
];

export const routeData = {
  'patna-to-gaya': { from: 'Patna', to: 'Gaya', distance: '105 km', time: '2 hr 45 min', fare: '₹1,899', note: 'The easy way to reach Bodh Gaya, without the station shuffle.' },
  'patna-to-muzaffarpur': { from: 'Patna', to: 'Muzaffarpur', distance: '85 km', time: '2 hr 15 min', fare: '₹1,699', note: 'A calm, direct ride north whenever you need it.' },
  'patna-to-darbhanga': { from: 'Patna', to: 'Darbhanga', distance: '145 km', time: '3 hr 40 min', fare: '₹2,399', note: 'Door-to-door travel for family visits and work trips.' },
  'patna-to-bhagalpur': { from: 'Patna', to: 'Bhagalpur', distance: '250 km', time: '5 hr 50 min', fare: '₹3,699', note: 'Settle in for the long road, with a driver you can trust.' },
  'saharsa-to-patna': { from: 'Saharsa', to: 'Patna', distance: '220 km', time: '5 hr 20 min', fare: '₹3,299', note: 'A reliable connection to the capital, morning or late evening.' },
  'darbhanga-to-raxaul': { from: 'Darbhanga', to: 'Raxaul', distance: '170 km', time: '4 hr 20 min', fare: '₹2,799', note: 'Cross-town to cross-border, with the details handled.' },
};

export const recentRides = [
  { id: 'RD-8421', route: 'Patna Airport → Boring Road', date: '18 Feb 2025', amount: '₹420', type: 'City ride', status: 'Completed' },
  { id: 'RD-8369', route: 'Patna → Gaya', date: '02 Feb 2025', amount: '₹2,040', type: 'Outstation', status: 'Completed' },
  { id: 'RD-8218', route: 'Rajendra Nagar → Patna Junction', date: '21 Jan 2025', amount: '₹180', type: 'City ride', status: 'Completed' },
];

export const cabs = [
  { id: 'mini', name: 'ROD Mini', detail: 'Swift Dzire or similar', passengers: 4, luggage: 2, eta: '4 min', price: 420, tag: 'Everyday favourite', tone: 'navy' },
  { id: 'sedan', name: 'ROD Sedan', detail: 'Honda Amaze or similar', passengers: 4, luggage: 3, eta: '7 min', price: 560, tag: 'More legroom', tone: 'teal' },
  { id: 'suv', name: 'ROD SUV', detail: 'Ertiga or similar', passengers: 6, luggage: 4, eta: '9 min', price: 780, tag: 'Best for groups', tone: 'saffron' },
];